version: "3.10"


# volumes:
#     postgres-data: {}


services:

  db:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=caleb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456


  web:
    build:
      context: .
      dockerfile: django-stripe-payment.Dockerfile
      command: ./docker-entrypoint.sh
    volumes:
      - .:/app
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
        # Stripe specific keys
        - STRIPE_PUBLIC_KEY=pk_test_51LhnkZBuTR45oMzij5F9bg94PJaqTd1v0Q4TIWKn3hZGm2oL0HFxWhXIkupFBRF7KcusEcpUvrVahwSyP1eLJhTE00S3IiqKnQ
        - STRIPE_SECRET_KEY=sk_test_51LhnkZBuTR45oMzinugmk60Ij1CAkcdI6E1dkoBDryV5ohUekeqYqj5jYuLAYH3lfqXM0M9s2AWXxJrqLO1mDzHK00wsiH1UTV
        - DJSTRIPE_TEST_WEBHOOK_SECRET=whsec_49db299643cbb3508123707f1d28d8b178ef2a11c134eb5dbf920a42a0275b17

        # Database Specific Settings
        - DJSTRIPE_TEST_DB_VENDOR=postgres
        - DJSTRIPE_TEST_DB_PORT=5432
        - DJSTRIPE_TEST_DB_USER=root
        - DJSTRIPE_TEST_DB_NAME=random_number
        - DJSTRIPE_TEST_DB_PASS=random_number
        - DJSTRIPE_TEST_DB_HOST=db

  stripe:
    image: stripe/stripe-cli:v1.7.4
    command: listen --forward-to http://web:8000/djstripe/webhook/
    depends_on:
      - web
    environment:
      - STRIPE_API_KEY=sk_test_51LhnkZBuTR45oMzinugmk60Ij1CAkcdI6E1dkoBDryV5ohUekeqYqj5jYuLAYH3lfqXM0M9s2AWXxJrqLO1mDzHK00wsiH1UTV
      - STRIPE_DEVICE_NAME=djstripe_docker 
